base_url = "https://nequissimus.com"
build_search_index = false
compile_sass = true
default_language = "en"
description = "Tim Steinbach"
highlight_code = true
theme = "zola-academic"
title = "NeQuissimus"

[extra]
author = "Tim Steinbach"
contact_links = []
experience = [
  { company = "Shopify", start_year = 2021, title = "Senior Data Developer - Lakehouse", tasks = [
    "Facilitating lakehouse scaling as project champion/leader",
    "Creation of high-velocity data pipelines",
    "Mentoring team members",
  ] },
  { company = "eSentire", start_year = 2020, end_year = 2021, title = "Manager - Advanced Threat Analytics", tasks = [
    "Enabling the success of a small team, multiple research students and co-ops",
    "Supporting the personal growth of a diverse team",
    "Interface between research division and other parts of the organization",
    "Using Machine Learning to detect adversarial tactics and techniques"
  ] },
  { company = "eSentire", start_year = 2018, end_year = 2020, title = "Senior Software Developer", tasks = [
    "High-performance data pipelines using Kafka Streams, Scala, deeplearning4j for machine learning",
    "Sumologic integration for ML-based detection of suspicious VPN connections",
    "Mentoring of junior team members and co-op students",
    "Coordination between security researchers and software developers",
    "Formulated goals, tasks, work units and managed stakeholder expectations"
  ] },
  { company = "eSentire", start_year = 2016, end_year = 2018, title = "Software Developer", tasks = [
    "Cloud-based logging application using ElasticSearch",
    "Internal REST services using Scalaz, Akka HTTP, Gatling",
    "Architecture and design of pipelines for ML-based data analysis",
    "SBT plugins to generate documentation from code and produce Kubernetes manifests"
  ] },
  { company = "Exinda Networks", start_year = 2016, end_year = 2016, title = "Software Developer & Team Lead", tasks = [
    "Centralized management and data analysis using Java EE, Cassandra, Spark"
  ] },
  { company = "Trustwave", start_year = 2015, end_year = 2016, title = "Senior Software Engineer", tasks = [
    "Lead developer for Trustwave MSS SIEM"
  ] },
  { company = "Trustwave", start_year = 2013, end_year = 2015, title = "Software Engineer", tasks = [
    "Development, release management and support for existing products",
  ] },
  { company = "RWE IT GmbH", start_year = 2009, end_year = 2011, title = "Software Consultant", tasks = [
    "Java EE, EJB 3.0, JPA, SAP Workflow, SAP Web Dynpro for Java, Adobe Flex, SAP BPM for Netweaver CE 7.2"
  ] }
]

interests = []
menu_left = []
menu_right = [
  { name = "Publications", link = "/#publications" },
  { name = "YouTube", link = "/#youtube" }
]
portrait = "/tim_steinbach_small.jpg"
organizations = []
role = "Scala Developer, Data Wrangler, Leader"
social_icons = [
  {icon="fa-book", icon_pack="fas", link="http://markdownbyexample.com" },
  {icon="fa-github", icon_pack="fab", link="https://github.com/NeQuissimus" },
  {icon="fa-linkedin", icon_pack="fab", link="https://www.linkedin.com/in/timsteinbach" },
  {icon="fa-twitter", icon_pack="fab", link="https://twitter.com/Tim_Steinbach" }
]
youtube = [
  {id = "8g8dNnLTIm8", description = "Get out of my cloud! Detecting cloud enumeration attacks using Machine Learning (Ai4 2021)"},
  {id = "_LDzO5_d1a0", description = "Sane System Management with NixOS - I Do Declare! (LambdaConf 2019)"},
  {id = "B8MEz-lPOq4", description = "Refined JSON - Making sense of stringly-typed data (Scala Up North 2018)"}
]

colorscheme = "default"
title_logo = "logo_gradient.png"
show_publications = true
show_youtube = true
